name: CI

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
  push:
    branches: [ main ]
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
  workflow_dispatch:

jobs:
  integrate:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Docker Compose
        run: docker-compose up -d postgres rabbitmq

      - name: Integration & Unit Test
        run: dotnet test -c Debug

      - name: Mutation Test
        run: |
          dotnet tool install -g dotnet-stryker
          dotnet stryker -s TemplatePostgreSQL.sln

      - name: Publish Final Mutation Report
        uses: actions/upload-artifact@v4
        with:
          name: mutation-report
          path: ~/**/mutation-report.html